This is makeindex, version 2.15 [TeX Live 2021] (kpathsea + Thai support).
Scanning style file ./Burkman_Prospectus_09_21_22.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file Burkman_Prospectus_09_21_22.acn....done (35 entries accepted, 0 rejected).
Sorting entries....done (194 comparisons).
Generating output file Burkman_Prospectus_09_21_22.acr....done (32 lines written, 0 warnings).
Output written in Burkman_Prospectus_09_21_22.acr.
Transcript written in Burkman_Prospectus_09_21_22.alg.
